#!/usr/bin/env python3
"""
cs_coordinate_converter.py
==========================
Auto-generated by 03_generate_converter.py

Converts coordinates from IWGSC CS RefSeq v2.1 to target wheat assemblies
using precomputed PCHIP spline conversion tables.

Usage
-----
from cs_coordinate_converter import CSCoordinateConverter

conv = CSCoordinateConverter("/path/to/conversion_tables")

# Single position
tgt_chr, tgt_pos, confidence = conv.convert("Chr1A", 500_000_000, "Mace")

# Region
tgt_chr, tgt_start, tgt_end, confidence = conv.convert_region("Chr1A", 490e6, 510e6, "Mace")

# BED file
result_df = conv.convert_bed("my_regions.bed", "SY_Mattis")

# List available targets
print(conv.available_targets())

# List chromosomes for a target
print(conv.available_chromosomes("Mace"))

Confidence (anchor_fraction)
----------------------------
Each conversion returns anchor_fraction (0.0-1.0):
  fraction of CS genes within +/-5 Mb recovered as anchors in target assembly.
  >= 0.8  : High confidence
  0.5-0.8 : Moderate confidence (sparse region or introgression)
  < 0.5   : Low confidence (assembly gap or highly diverged region)

Note: tgt_chr may vary along a chromosome for assemblies with known translocations
(e.g. ArinaLrFor Chr5B maps to Chr5B proximally and Chr7B distally).
"""

import gzip
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d


class CSCoordinateConverter:
    """
    Converts CS v2.1 coordinates to target assembly coordinates using
    precomputed PCHIP spline conversion tables.
    """

    CONFIDENCE_HIGH     = 0.8
    CONFIDENCE_MODERATE = 0.5

    def __init__(self, conversion_tables_dir):
        self.conv_dir = Path(conversion_tables_dir)
        if not self.conv_dir.exists():
            raise FileNotFoundError(f"Conversion tables directory not found: {self.conv_dir}")
        self._tables = {}

    def available_targets(self):
        return sorted([d.name for d in self.conv_dir.iterdir() if d.is_dir()])

    def available_chromosomes(self, target_name):
        tgt_dir = self.conv_dir / target_name
        if not tgt_dir.exists():
            raise ValueError(f"Target not found: {target_name}")
        return sorted([
            f.name.replace("_conversion.tsv.gz", "")
            for f in tgt_dir.glob("*_conversion.tsv.gz")
        ])

    def _load_table(self, target_name, cs_chr):
        key = (target_name, cs_chr)
        if key in self._tables:
            return self._tables[key]
        table_file = self.conv_dir / target_name / f"{cs_chr}_conversion.tsv.gz"
        if not table_file.exists():
            alt = cs_chr.replace("chr", "Chr")
            table_file = self.conv_dir / target_name / f"{alt}_conversion.tsv.gz"
            if not table_file.exists():
                raise FileNotFoundError(
                    f"No conversion table for {target_name}/{cs_chr}. "
                    f"Available: {self.available_chromosomes(target_name)}"
                )
        df = pd.read_csv(table_file, sep="\t", compression="gzip")
        self._tables[key] = df
        return df

    def _get_interpolators(self, target_name, cs_chr):
        """
        Build interpolators from table. Returns dict keyed by tgt_chr,
        each with (cs_pos_array, interp_pos, interp_fraction).
        For standard chromosomes the dict has one key.
        For translocated chromosomes (e.g. ArinaLrFor Chr5B) it has two keys,
        one per segment (Chr5B proximal, Chr7B distal).
        """
        cache_key = f"interp_{target_name}_{cs_chr}"
        if hasattr(self, cache_key):
            return getattr(self, cache_key)

        df = self._load_table(target_name, cs_chr)
        segments = {}

        for tgt_chr, grp in df.groupby("tgt_chr"):
            grp = grp.sort_values("cs_pos").reset_index(drop=True)
            cs_pos = grp["cs_pos"].values
            tgt_pos = grp["tgt_pos"].values

            # anchor_fraction column (new); fall back to density-based proxy if absent
            if "anchor_fraction" in grp.columns:
                conf_vals = grp["anchor_fraction"].fillna(0).values
            else:
                d = grp["anchor_density_5Mb"].values
                conf_vals = np.clip(d / 50.0, 0, 1)

            interp_pos = interp1d(cs_pos, tgt_pos, kind="linear",
                                   bounds_error=False,
                                   fill_value=(tgt_pos[0], tgt_pos[-1]))
            interp_conf = interp1d(cs_pos, conf_vals, kind="linear",
                                    bounds_error=False,
                                    fill_value=(conf_vals[0], conf_vals[-1]))
            segments[tgt_chr] = {
                "cs_min": float(cs_pos[0]),
                "cs_max": float(cs_pos[-1]),
                "interp_pos":  interp_pos,
                "interp_conf": interp_conf,
            }

        setattr(self, cache_key, segments)
        return segments

    def _segment_for_pos(self, segments, cs_pos):
        """Return the segment whose cs range contains cs_pos (nearest if multiple)."""
        if len(segments) == 1:
            return next(iter(segments.values()))
        best_tgt, best_dist = None, float("inf")
        for tgt_chr, seg in segments.items():
            if seg["cs_min"] <= cs_pos <= seg["cs_max"]:
                return seg
            dist = min(abs(cs_pos - seg["cs_min"]), abs(cs_pos - seg["cs_max"]))
            if dist < best_dist:
                best_dist, best_tgt = dist, tgt_chr
        return segments[best_tgt]

    def _tgt_chr_for_pos(self, segments, cs_pos):
        if len(segments) == 1:
            return next(iter(segments.keys()))
        for tgt_chr, seg in segments.items():
            if seg["cs_min"] <= cs_pos <= seg["cs_max"]:
                return tgt_chr
        # Nearest
        return min(segments.keys(),
                   key=lambda t: min(abs(cs_pos - segments[t]["cs_min"]),
                                     abs(cs_pos - segments[t]["cs_max"])))

    def convert(self, cs_chr, cs_position, target_name):
        """
        Convert a single CS position to target coordinates.

        Returns
        -------
        tgt_chr : str
        tgt_position : int
        anchor_fraction : float  (0.0-1.0 confidence)
        """
        segments = self._get_interpolators(target_name, cs_chr)
        seg = self._segment_for_pos(segments, cs_position)
        tgt_chr = self._tgt_chr_for_pos(segments, cs_position)
        tgt_pos = int(np.round(seg["interp_pos"](cs_position)))
        conf = float(np.clip(seg["interp_conf"](cs_position), 0, 1))
        return tgt_chr, tgt_pos, conf

    def confidence_label(self, anchor_fraction):
        if anchor_fraction >= self.CONFIDENCE_HIGH:
            return "High"
        elif anchor_fraction >= self.CONFIDENCE_MODERATE:
            return "Moderate"
        return "Low"

    def convert_region(self, cs_chr, cs_start, cs_end, target_name):
        """
        Convert a CS region to target coordinates.

        For translocated chromosomes, if the region spans a segment boundary
        the returned tgt_chr will be from the dominant (larger) segment.

        Returns
        -------
        tgt_chr : str
        tgt_start : int
        tgt_end : int
        anchor_fraction : float  mean confidence across region (0.0-1.0)
        """
        segments = self._get_interpolators(target_name, cs_chr)

        # Proportional sampling: 1 per 5 Mb, capped at 50, min 1
        region_size = max(0, cs_end - cs_start)
        n_samples = max(1, min(50, int(region_size / 5_000_000) + 1))
        sample_pts = np.linspace(cs_start, cs_end, n_samples)

        tgt_start_seg = self._segment_for_pos(segments, cs_start)
        tgt_end_seg   = self._segment_for_pos(segments, cs_end)
        tgt_chr = self._tgt_chr_for_pos(segments, (cs_start + cs_end) / 2)

        tgt_start = int(np.round(tgt_start_seg["interp_pos"](cs_start)))
        tgt_end   = int(np.round(tgt_end_seg["interp_pos"](cs_end)))

        conf_vals = []
        for pt in sample_pts:
            seg = self._segment_for_pos(segments, pt)
            conf_vals.append(float(np.clip(seg["interp_conf"](pt), 0, 1)))
        mean_conf = float(np.mean(conf_vals))

        return tgt_chr, min(tgt_start, tgt_end), max(tgt_start, tgt_end), mean_conf

    def convert_bed(self, bed_file, target_name, output_file=None):
        """
        Convert all regions in a BED file to target coordinates.

        Returns DataFrame with columns:
          cs_chr, cs_start, cs_end, tgt_chr, tgt_start, tgt_end,
          anchor_fraction, confidence_label
        """
        df = pd.read_csv(bed_file, sep="\t", header=None, comment="#")
        n_cols = len(df.columns)
        col_names = ["cs_chr", "cs_start", "cs_end"] + [f"col{i}" for i in range(3, n_cols)]
        df.columns = col_names

        results = []
        failed = 0

        for _, row in df.iterrows():
            try:
                tgt_chr, tgt_start, tgt_end, conf = self.convert_region(
                    row["cs_chr"], row["cs_start"], row["cs_end"], target_name
                )
                result_row = {
                    "cs_chr":           row["cs_chr"],
                    "cs_start":         row["cs_start"],
                    "cs_end":           row["cs_end"],
                    "tgt_chr":          tgt_chr,
                    "tgt_start":        tgt_start,
                    "tgt_end":          tgt_end,
                    "anchor_fraction":  round(conf, 3),
                    "confidence_label": self.confidence_label(conf),
                }
                for i in range(3, n_cols):
                    result_row[f"col{i}"] = row[f"col{i}"]
                results.append(result_row)
            except (FileNotFoundError, KeyError) as e:
                failed += 1
                if failed <= 5:
                    print(f"WARN: {row['cs_chr']}:{row['cs_start']}-{row['cs_end']}: {e}",
                          file=sys.stderr)

        result_df = pd.DataFrame(results)
        if output_file:
            result_df.to_csv(output_file, sep="\t", index=False)
            print(f"Saved: {output_file}", file=sys.stderr)
        return result_df

    def __repr__(self):
        targets = self.available_targets()
        return (f"CSCoordinateConverter({len(targets)} targets, "
                f"dir={self.conv_dir})")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="CS coordinate converter CLI")
    parser.add_argument("--tables-dir", required=True)
    parser.add_argument("--target",     required=True)
    parser.add_argument("--chr",        help="CS chromosome (e.g. Chr1A)")
    parser.add_argument("--pos",        type=int, help="Single position (bp)")
    parser.add_argument("--start",      type=int, help="Region start (bp)")
    parser.add_argument("--end",        type=int, help="Region end (bp)")
    parser.add_argument("--bed",        help="BED file to convert")
    parser.add_argument("--output",     help="Output file for BED conversion")
    args = parser.parse_args()

    conv = CSCoordinateConverter(args.tables_dir)

    if args.bed:
        df = conv.convert_bed(args.bed, args.target, output_file=args.output)
        if not args.output:
            print(df.to_csv(sep="\t", index=False))
    elif args.chr and args.pos is not None:
        tgt_chr, tgt_pos, conf = conv.convert(args.chr, args.pos, args.target)
        label = conv.confidence_label(conf)
        print(f"{args.chr}:{args.pos} -> {tgt_chr}:{tgt_pos} "
              f"(anchor_fraction={conf:.3f}, {label})")
    elif args.chr and args.start is not None and args.end is not None:
        tgt_chr, s, e, conf = conv.convert_region(args.chr, args.start, args.end, args.target)
        label = conv.confidence_label(conf)
        print(f"{args.chr}:{args.start}-{args.end} -> {tgt_chr}:{s}-{e} "
              f"(anchor_fraction={conf:.3f}, {label})")
    else:
        print("Available targets:", conv.available_targets())
