# cs_coordinate_converter.R
# ==========================
# Auto-generated by 03_generate_converter.py
#
# Converts coordinates from IWGSC CS RefSeq v2.1 to target wheat assemblies.
#
# Usage:
#   source("cs_coordinate_converter.R")
#   conv <- load_cs_converter("path/to/conversion_tables")
#
#   # Single position
#   res <- cs_convert(conv, "Chr1A", 500e6, "Mace")
#   cat(res$tgt_chr, res$tgt_pos, res$anchor_fraction, "\n")
#
#   # Region
#   res <- cs_convert_region(conv, "Chr1A", 490e6, 510e6, "Mace")
#
#   # BED data frame
#   result_df <- cs_convert_bed(conv, my_bed_df, "SY_Mattis")
#
# Confidence (anchor_fraction 0.0-1.0):
#   >= 0.8  : High confidence
#   0.5-0.8 : Moderate confidence
#   < 0.5   : Low confidence

library(data.table)

CONFIDENCE_HIGH     <- 0.8
CONFIDENCE_MODERATE <- 0.5

#' Load coordinate converter
#' @param tables_dir Path to conversion_tables/ directory
#' @return Converter object
load_cs_converter <- function(tables_dir) {
  if (!dir.exists(tables_dir)) stop(paste("Not found:", tables_dir))
  conv <- list(tables_dir = tables_dir, cache = list())
  class(conv) <- "CSConverter"
  conv
}

cs_list_targets <- function(conv) {
  sort(list.dirs(conv$tables_dir, full.names=FALSE, recursive=FALSE))
}

cs_list_chromosomes <- function(conv, target_name) {
  files <- list.files(file.path(conv$tables_dir, target_name),
                      pattern="_conversion\\.tsv\\.gz$")
  gsub("_conversion\\.tsv\\.gz", "", files)
}

.load_table <- function(conv, target_name, cs_chr) {
  key <- paste(target_name, cs_chr, sep="_")
  if (!is.null(conv$cache[[key]])) return(conv$cache[[key]])
  f <- file.path(conv$tables_dir, target_name, paste0(cs_chr, "_conversion.tsv.gz"))
  if (!file.exists(f)) {
    alt <- sub("^chr", "Chr", cs_chr)
    f <- file.path(conv$tables_dir, target_name, paste0(alt, "_conversion.tsv.gz"))
    if (!file.exists(f)) stop(paste("No table for", target_name, cs_chr))
  }
  dt <- fread(f)
  # Add anchor_fraction proxy if column absent (old tables)
  if (!"anchor_fraction" %in% names(dt)) {
    dt[, anchor_fraction := pmin(anchor_density_5Mb / 50, 1.0)]
  }
  conv$cache[[key]] <<- dt
  dt
}

.confidence_label <- function(f) {
  ifelse(f >= CONFIDENCE_HIGH, "High",
         ifelse(f >= CONFIDENCE_MODERATE, "Moderate", "Low"))
}

#' Convert a single CS position
#' @return Named list: tgt_chr, tgt_pos, anchor_fraction, confidence_label
cs_convert <- function(conv, cs_chr, cs_pos, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  # Use tgt_chr at nearest position
  idx <- which.min(abs(dt$cs_pos - cs_pos))
  tgt_chr <- dt$tgt_chr[idx]
  seg <- dt[tgt_chr == tgt_chr]
  tgt_pos <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_pos, rule=2)$y)
  conf    <- as.numeric(approx(seg$cs_pos, seg$anchor_fraction, xout=cs_pos, rule=2)$y)
  conf    <- max(0, min(1, conf))
  list(tgt_chr=tgt_chr, tgt_pos=tgt_pos,
       anchor_fraction=round(conf, 3),
       confidence_label=.confidence_label(conf))
}

#' Convert a CS region
#' @return Named list: tgt_chr, tgt_start, tgt_end, anchor_fraction, confidence_label
cs_convert_region <- function(conv, cs_chr, cs_start, cs_end, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  mid_idx <- which.min(abs(dt$cs_pos - (cs_start + cs_end) / 2))
  tgt_chr <- dt$tgt_chr[mid_idx]
  seg <- dt[tgt_chr == tgt_chr]
  tgt_start <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_start, rule=2)$y)
  tgt_end   <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_end,   rule=2)$y)
  # Proportional sampling: 1 per 5 Mb, capped at 50
  n_samp <- max(1L, min(50L, as.integer((cs_end - cs_start) / 5e6) + 1L))
  pts <- seq(cs_start, cs_end, length.out=n_samp)
  conf_vals <- approx(seg$cs_pos, seg$anchor_fraction, xout=pts, rule=2)$y
  mean_conf <- mean(pmax(0, pmin(1, conf_vals)))
  list(tgt_chr=tgt_chr,
       tgt_start=min(tgt_start, tgt_end),
       tgt_end=max(tgt_start, tgt_end),
       anchor_fraction=round(mean_conf, 3),
       confidence_label=.confidence_label(mean_conf))
}

#' Convert a data frame of BED regions
#' @param bed_df Data frame with columns: chr, start, end
#' @return Data frame with tgt_chr, tgt_start, tgt_end, anchor_fraction, confidence_label
cs_convert_bed <- function(conv, bed_df, target_name) {
  colnames(bed_df)[1:3] <- c("cs_chr", "cs_start", "cs_end")
  results <- lapply(seq_len(nrow(bed_df)), function(i) {
    tryCatch({
      r <- cs_convert_region(conv, bed_df$cs_chr[i],
                             bed_df$cs_start[i], bed_df$cs_end[i], target_name)
      data.frame(cs_chr=bed_df$cs_chr[i], cs_start=bed_df$cs_start[i],
                 cs_end=bed_df$cs_end[i], tgt_chr=r$tgt_chr,
                 tgt_start=r$tgt_start, tgt_end=r$tgt_end,
                 anchor_fraction=r$anchor_fraction,
                 confidence_label=r$confidence_label,
                 stringsAsFactors=FALSE)
    }, error=function(e) { warning(paste("Row", i, "failed:", e$message)); NULL })
  })
  result_df <- do.call(rbind, Filter(Negate(is.null), results))
  if (ncol(bed_df) > 3) {
    ok <- !sapply(results, is.null)
    result_df <- cbind(result_df, bed_df[ok, 4:ncol(bed_df), drop=FALSE])
  }
  result_df
}

print.CSConverter <- function(conv, ...) {
  cat("CS Coordinate Converter\n")
  cat("Tables dir:", conv$tables_dir, "\n")
  cat("Targets:", paste(cs_list_targets(conv), collapse=", "), "\n")
}
