#!/usr/bin/env python3
"""
03_generate_converter.py
========================
Generates ready-to-use coordinate conversion utilities:
  - cs_coordinate_converter.py  (Python class, importable)
  - cs_coordinate_converter.R   (R functions)

Both load the conversion tables on demand and provide:
  convert(cs_chr, cs_position, target_name) -> (tgt_chr, tgt_position, anchor_fraction)
  convert_region(cs_chr, cs_start, cs_end, target_name) -> (tgt_chr, tgt_start, tgt_end, anchor_fraction)
  convert_bed(input_bed, target_name) -> DataFrame
"""

import argparse
import sys
from pathlib import Path


PYTHON_CONVERTER = '''#!/usr/bin/env python3
"""
cs_coordinate_converter.py
==========================
Auto-generated by 03_generate_converter.py

Converts coordinates from IWGSC CS RefSeq v2.1 to target wheat assemblies
using precomputed PCHIP spline conversion tables.

Usage
-----
from cs_coordinate_converter import CSCoordinateConverter

conv = CSCoordinateConverter("/path/to/conversion_tables")

# Single position
tgt_chr, tgt_pos, confidence = conv.convert("Chr1A", 500_000_000, "Mace")

# Region
tgt_chr, tgt_start, tgt_end, confidence = conv.convert_region("Chr1A", 490e6, 510e6, "Mace")

# BED file
result_df = conv.convert_bed("my_regions.bed", "SY_Mattis")

# List available targets
print(conv.available_targets())

# List chromosomes for a target
print(conv.available_chromosomes("Mace"))

Confidence (anchor_fraction)
----------------------------
Each conversion returns anchor_fraction (0.0-1.0):
  fraction of CS genes within +/-5 Mb recovered as anchors in target assembly.
  >= 0.8  : High confidence
  0.5-0.8 : Moderate confidence (sparse region or introgression)
  < 0.5   : Low confidence (assembly gap or highly diverged region)

Note: tgt_chr may vary along a chromosome for assemblies with known translocations
(e.g. ArinaLrFor Chr5B maps to Chr5B proximally and Chr7B distally).
"""

import gzip
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d


class CSCoordinateConverter:
    """
    Converts CS v2.1 coordinates to target assembly coordinates using
    precomputed PCHIP spline conversion tables.
    """

    CONFIDENCE_HIGH     = 0.8
    CONFIDENCE_MODERATE = 0.5

    def __init__(self, conversion_tables_dir):
        self.conv_dir = Path(conversion_tables_dir)
        if not self.conv_dir.exists():
            raise FileNotFoundError(f"Conversion tables directory not found: {self.conv_dir}")
        self._tables = {}

    def available_targets(self):
        return sorted([d.name for d in self.conv_dir.iterdir() if d.is_dir()])

    def available_chromosomes(self, target_name):
        tgt_dir = self.conv_dir / target_name
        if not tgt_dir.exists():
            raise ValueError(f"Target not found: {target_name}")
        return sorted([
            f.name.replace("_conversion.tsv.gz", "")
            for f in tgt_dir.glob("*_conversion.tsv.gz")
        ])

    def _load_table(self, target_name, cs_chr):
        key = (target_name, cs_chr)
        if key in self._tables:
            return self._tables[key]
        table_file = self.conv_dir / target_name / f"{cs_chr}_conversion.tsv.gz"
        if not table_file.exists():
            alt = cs_chr.replace("chr", "Chr")
            table_file = self.conv_dir / target_name / f"{alt}_conversion.tsv.gz"
            if not table_file.exists():
                raise FileNotFoundError(
                    f"No conversion table for {target_name}/{cs_chr}. "
                    f"Available: {self.available_chromosomes(target_name)}"
                )
        df = pd.read_csv(table_file, sep="\\t", compression="gzip")
        # Strip assembly prefix from target columns for internal use
        # e.g. Jagger_tgt_chr -> tgt_chr, Jagger_anchor_fraction -> anchor_fraction
        prefix = target_name + "_"
        rename = {c: c[len(prefix):] for c in df.columns if c.startswith(prefix)}
        if rename:
            df = df.rename(columns=rename)
        self._tables[key] = df
        return df

    def _get_interpolators(self, target_name, cs_chr):
        """
        Build interpolators from table. Returns dict keyed by tgt_chr,
        each with (cs_pos_array, interp_pos, interp_fraction).
        For standard chromosomes the dict has one key.
        For translocated chromosomes (e.g. ArinaLrFor Chr5B) it has two keys,
        one per segment (Chr5B proximal, Chr7B distal).
        """
        cache_key = f"interp_{target_name}_{cs_chr}"
        if hasattr(self, cache_key):
            return getattr(self, cache_key)

        df = self._load_table(target_name, cs_chr)
        segments = {}

        for tgt_chr, grp in df.groupby("tgt_chr"):
            grp = grp.sort_values("cs_pos").reset_index(drop=True)
            cs_pos = grp["cs_pos"].values
            tgt_pos = grp["tgt_pos"].values

            # anchor_fraction column (new); fall back to density-based proxy if absent
            if "anchor_fraction" in grp.columns:
                conf_vals = grp["anchor_fraction"].fillna(0).values
            else:
                d = grp["anchor_density_5Mb"].values
                conf_vals = np.clip(d / 50.0, 0, 1)

            interp_pos = interp1d(cs_pos, tgt_pos, kind="linear",
                                   bounds_error=False,
                                   fill_value=(tgt_pos[0], tgt_pos[-1]))
            interp_conf = interp1d(cs_pos, conf_vals, kind="linear",
                                    bounds_error=False,
                                    fill_value=(conf_vals[0], conf_vals[-1]))
            segments[tgt_chr] = {
                "cs_min": float(cs_pos[0]),
                "cs_max": float(cs_pos[-1]),
                "interp_pos":  interp_pos,
                "interp_conf": interp_conf,
            }

        setattr(self, cache_key, segments)
        return segments

    def _segment_for_pos(self, segments, cs_pos):
        """Return the segment whose cs range contains cs_pos (nearest if multiple)."""
        if len(segments) == 1:
            return next(iter(segments.values()))
        best_tgt, best_dist = None, float("inf")
        for tgt_chr, seg in segments.items():
            if seg["cs_min"] <= cs_pos <= seg["cs_max"]:
                return seg
            dist = min(abs(cs_pos - seg["cs_min"]), abs(cs_pos - seg["cs_max"]))
            if dist < best_dist:
                best_dist, best_tgt = dist, tgt_chr
        return segments[best_tgt]

    def _tgt_chr_for_pos(self, segments, cs_pos):
        if len(segments) == 1:
            return next(iter(segments.keys()))
        for tgt_chr, seg in segments.items():
            if seg["cs_min"] <= cs_pos <= seg["cs_max"]:
                return tgt_chr
        # Nearest
        return min(segments.keys(),
                   key=lambda t: min(abs(cs_pos - segments[t]["cs_min"]),
                                     abs(cs_pos - segments[t]["cs_max"])))

    def convert(self, cs_chr, cs_position, target_name):
        """
        Convert a single CS position to target coordinates.

        Returns
        -------
        tgt_chr : str
        tgt_position : int
        anchor_fraction : float  (0.0-1.0 confidence)
        """
        segments = self._get_interpolators(target_name, cs_chr)
        seg = self._segment_for_pos(segments, cs_position)
        tgt_chr = self._tgt_chr_for_pos(segments, cs_position)
        tgt_pos = int(np.round(seg["interp_pos"](cs_position)))
        conf = float(np.clip(seg["interp_conf"](cs_position), 0, 1))
        return tgt_chr, tgt_pos, conf

    def confidence_label(self, anchor_fraction):
        if anchor_fraction >= self.CONFIDENCE_HIGH:
            return "High"
        elif anchor_fraction >= self.CONFIDENCE_MODERATE:
            return "Moderate"
        return "Low"

    def convert_region(self, cs_chr, cs_start, cs_end, target_name):
        """
        Convert a CS region to target coordinates.

        For translocated chromosomes, if the region spans a segment boundary
        the returned tgt_chr will be from the dominant (larger) segment.

        Returns
        -------
        tgt_chr : str
        tgt_start : int
        tgt_end : int
        anchor_fraction : float  mean confidence across region (0.0-1.0)
        """
        segments = self._get_interpolators(target_name, cs_chr)

        # Proportional sampling: 1 per 5 Mb, capped at 50, min 1
        region_size = max(0, cs_end - cs_start)
        n_samples = max(1, min(50, int(region_size / 5_000_000) + 1))
        sample_pts = np.linspace(cs_start, cs_end, n_samples)

        tgt_start_seg = self._segment_for_pos(segments, cs_start)
        tgt_end_seg   = self._segment_for_pos(segments, cs_end)
        tgt_chr = self._tgt_chr_for_pos(segments, (cs_start + cs_end) / 2)

        tgt_start = int(np.round(tgt_start_seg["interp_pos"](cs_start)))
        tgt_end   = int(np.round(tgt_end_seg["interp_pos"](cs_end)))

        conf_vals = []
        for pt in sample_pts:
            seg = self._segment_for_pos(segments, pt)
            conf_vals.append(float(np.clip(seg["interp_conf"](pt), 0, 1)))
        mean_conf = float(np.mean(conf_vals))

        return tgt_chr, min(tgt_start, tgt_end), max(tgt_start, tgt_end), mean_conf

    def convert_bed(self, bed_file, target_name, output_file=None):
        """
        Convert all regions in a BED file to target coordinates.

        Returns DataFrame with columns:
          cs_chr, cs_start, cs_end, tgt_chr, tgt_start, tgt_end,
          anchor_fraction, confidence_label
        """
        df = pd.read_csv(bed_file, sep="\\t", header=None, comment="#")
        n_cols = len(df.columns)
        col_names = ["cs_chr", "cs_start", "cs_end"] + [f"col{i}" for i in range(3, n_cols)]
        df.columns = col_names

        results = []
        failed = 0

        for _, row in df.iterrows():
            try:
                tgt_chr, tgt_start, tgt_end, conf = self.convert_region(
                    row["cs_chr"], row["cs_start"], row["cs_end"], target_name
                )
                result_row = {
                    "cs_chr":           row["cs_chr"],
                    "cs_start":         row["cs_start"],
                    "cs_end":           row["cs_end"],
                    "tgt_chr":          tgt_chr,
                    "tgt_start":        tgt_start,
                    "tgt_end":          tgt_end,
                    "anchor_fraction":  round(conf, 3),
                    "confidence_label": self.confidence_label(conf),
                }
                for i in range(3, n_cols):
                    result_row[f"col{i}"] = row[f"col{i}"]
                results.append(result_row)
            except (FileNotFoundError, KeyError) as e:
                failed += 1
                if failed <= 5:
                    print(f"WARN: {row[\'cs_chr\']}:{row[\'cs_start\']}-{row[\'cs_end\']}: {e}",
                          file=sys.stderr)

        result_df = pd.DataFrame(results)
        if output_file:
            result_df.to_csv(output_file, sep="\\t", index=False)
            print(f"Saved: {output_file}", file=sys.stderr)
        return result_df

    def __repr__(self):
        targets = self.available_targets()
        return (f"CSCoordinateConverter({len(targets)} targets, "
                f"dir={self.conv_dir})")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="CS coordinate converter CLI")
    parser.add_argument("--tables-dir", required=True)
    parser.add_argument("--target",     required=True)
    parser.add_argument("--chr",        help="CS chromosome (e.g. Chr1A)")
    parser.add_argument("--pos",        type=int, help="Single position (bp)")
    parser.add_argument("--start",      type=int, help="Region start (bp)")
    parser.add_argument("--end",        type=int, help="Region end (bp)")
    parser.add_argument("--bed",        help="BED file to convert")
    parser.add_argument("--output",     help="Output file for BED conversion")
    args = parser.parse_args()

    conv = CSCoordinateConverter(args.tables_dir)

    if args.bed:
        df = conv.convert_bed(args.bed, args.target, output_file=args.output)
        if not args.output:
            print(df.to_csv(sep="\\t", index=False))
    elif args.chr and args.pos is not None:
        tgt_chr, tgt_pos, conf = conv.convert(args.chr, args.pos, args.target)
        label = conv.confidence_label(conf)
        print(f"{args.chr}:{args.pos} -> {tgt_chr}:{tgt_pos} "
              f"(anchor_fraction={conf:.3f}, {label})")
    elif args.chr and args.start is not None and args.end is not None:
        tgt_chr, s, e, conf = conv.convert_region(args.chr, args.start, args.end, args.target)
        label = conv.confidence_label(conf)
        print(f"{args.chr}:{args.start}-{args.end} -> {tgt_chr}:{s}-{e} "
              f"(anchor_fraction={conf:.3f}, {label})")
    else:
        print("Available targets:", conv.available_targets())
'''


R_CONVERTER = '''# cs_coordinate_converter.R
# ==========================
# Auto-generated by 03_generate_converter.py
#
# Converts coordinates from IWGSC CS RefSeq v2.1 to target wheat assemblies.
#
# Usage:
#   source("cs_coordinate_converter.R")
#   conv <- load_cs_converter("path/to/conversion_tables")
#
#   # Single position
#   res <- cs_convert(conv, "Chr1A", 500e6, "Mace")
#   cat(res$tgt_chr, res$tgt_pos, res$anchor_fraction, "\\n")
#
#   # Region
#   res <- cs_convert_region(conv, "Chr1A", 490e6, 510e6, "Mace")
#
#   # BED data frame
#   result_df <- cs_convert_bed(conv, my_bed_df, "SY_Mattis")
#
# Confidence (anchor_fraction 0.0-1.0):
#   >= 0.8  : High confidence
#   0.5-0.8 : Moderate confidence
#   < 0.5   : Low confidence

library(data.table)

CONFIDENCE_HIGH     <- 0.8
CONFIDENCE_MODERATE <- 0.5

#\' Load coordinate converter
#\' @param tables_dir Path to conversion_tables/ directory
#\' @return Converter object
load_cs_converter <- function(tables_dir) {
  if (!dir.exists(tables_dir)) stop(paste("Not found:", tables_dir))
  conv <- list(tables_dir = tables_dir, cache = list())
  class(conv) <- "CSConverter"
  conv
}

cs_list_targets <- function(conv) {
  sort(list.dirs(conv$tables_dir, full.names=FALSE, recursive=FALSE))
}

cs_list_chromosomes <- function(conv, target_name) {
  files <- list.files(file.path(conv$tables_dir, target_name),
                      pattern="_conversion\\\\.tsv\\\\.gz$")
  gsub("_conversion\\\\.tsv\\\\.gz", "", files)
}

.load_table <- function(conv, target_name, cs_chr) {
  key <- paste(target_name, cs_chr, sep="_")
  if (!is.null(conv$cache[[key]])) return(conv$cache[[key]])
  f <- file.path(conv$tables_dir, target_name, paste0(cs_chr, "_conversion.tsv.gz"))
  if (!file.exists(f)) {
    alt <- sub("^chr", "Chr", cs_chr)
    f <- file.path(conv$tables_dir, target_name, paste0(alt, "_conversion.tsv.gz"))
    if (!file.exists(f)) stop(paste("No table for", target_name, cs_chr))
  }
  dt <- fread(f)
  # Strip assembly prefix from target columns
  # e.g. Jagger_tgt_chr -> tgt_chr, Jagger_anchor_fraction -> anchor_fraction
  prefix <- paste0(target_name, "_")
  setnames(dt, names(dt), sub(paste0("^", prefix), "", names(dt)))
  conv$cache[[key]] <<- dt
  dt
}

.confidence_label <- function(f) {
  ifelse(f >= CONFIDENCE_HIGH, "High",
         ifelse(f >= CONFIDENCE_MODERATE, "Moderate", "Low"))
}

#\' Convert a single CS position
#\' @return Named list: tgt_chr, tgt_pos, anchor_fraction, confidence_label
cs_convert <- function(conv, cs_chr, cs_pos, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  # Use tgt_chr at nearest position
  idx <- which.min(abs(dt$cs_pos - cs_pos))
  tgt_chr <- dt$tgt_chr[idx]
  seg <- dt[tgt_chr == tgt_chr]
  tgt_pos <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_pos, rule=2)$y)
  conf    <- as.numeric(approx(seg$cs_pos, seg$anchor_fraction, xout=cs_pos, rule=2)$y)
  conf    <- max(0, min(1, conf))
  list(tgt_chr=tgt_chr, tgt_pos=tgt_pos,
       anchor_fraction=round(conf, 3),
       confidence_label=.confidence_label(conf))
}

#\' Convert a CS region
#\' @return Named list: tgt_chr, tgt_start, tgt_end, anchor_fraction, confidence_label
cs_convert_region <- function(conv, cs_chr, cs_start, cs_end, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  mid_idx <- which.min(abs(dt$cs_pos - (cs_start + cs_end) / 2))
  tgt_chr <- dt$tgt_chr[mid_idx]
  seg <- dt[tgt_chr == tgt_chr]
  tgt_start <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_start, rule=2)$y)
  tgt_end   <- as.integer(approx(seg$cs_pos, seg$tgt_pos, xout=cs_end,   rule=2)$y)
  # Proportional sampling: 1 per 5 Mb, capped at 50
  n_samp <- max(1L, min(50L, as.integer((cs_end - cs_start) / 5e6) + 1L))
  pts <- seq(cs_start, cs_end, length.out=n_samp)
  conf_vals <- approx(seg$cs_pos, seg$anchor_fraction, xout=pts, rule=2)$y
  mean_conf <- mean(pmax(0, pmin(1, conf_vals)))
  list(tgt_chr=tgt_chr,
       tgt_start=min(tgt_start, tgt_end),
       tgt_end=max(tgt_start, tgt_end),
       anchor_fraction=round(mean_conf, 3),
       confidence_label=.confidence_label(mean_conf))
}

#\' Convert a data frame of BED regions
#\' @param bed_df Data frame with columns: chr, start, end
#\' @return Data frame with tgt_chr, tgt_start, tgt_end, anchor_fraction, confidence_label
cs_convert_bed <- function(conv, bed_df, target_name) {
  colnames(bed_df)[1:3] <- c("cs_chr", "cs_start", "cs_end")
  results <- lapply(seq_len(nrow(bed_df)), function(i) {
    tryCatch({
      r <- cs_convert_region(conv, bed_df$cs_chr[i],
                             bed_df$cs_start[i], bed_df$cs_end[i], target_name)
      data.frame(cs_chr=bed_df$cs_chr[i], cs_start=bed_df$cs_start[i],
                 cs_end=bed_df$cs_end[i], tgt_chr=r$tgt_chr,
                 tgt_start=r$tgt_start, tgt_end=r$tgt_end,
                 anchor_fraction=r$anchor_fraction,
                 confidence_label=r$confidence_label,
                 stringsAsFactors=FALSE)
    }, error=function(e) { warning(paste("Row", i, "failed:", e$message)); NULL })
  })
  result_df <- do.call(rbind, Filter(Negate(is.null), results))
  if (ncol(bed_df) > 3) {
    ok <- !sapply(results, is.null)
    result_df <- cbind(result_df, bed_df[ok, 4:ncol(bed_df), drop=FALSE])
  }
  result_df
}

print.CSConverter <- function(conv, ...) {
  cat("CS Coordinate Converter\\n")
  cat("Tables dir:", conv$tables_dir, "\\n")
  cat("Targets:", paste(cs_list_targets(conv), collapse=", "), "\\n")
}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--conversion-dir", required=True)
    parser.add_argument("--target-names", nargs="+", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()

    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)

    py_out = outdir / "cs_coordinate_converter.py"
    with open(py_out, "w") as fh:
        fh.write(PYTHON_CONVERTER)
    print(f"Written: {py_out}", file=sys.stderr)

    r_out = outdir / "cs_coordinate_converter.R"
    with open(r_out, "w") as fh:
        fh.write(R_CONVERTER)
    print(f"Written: {r_out}", file=sys.stderr)

    readme_out = outdir / "CONVERTER_USAGE.md"
    with open(readme_out, "w") as fh:
        fh.write(f"""# CS Coordinate Converter — Usage Guide

Generated from {len(args.target_names)} target assemblies.

## Available targets
{chr(10).join(f'- {t}' for t in sorted(args.target_names))}

## Confidence metric — anchor_fraction (0.0–1.0)
Proportion of CS v2.1 genes within ±5 Mb recovered as anchors in the target assembly.
Normalised by CS gene density so pericentromeric regions are not unfairly penalised.

| anchor_fraction | Confidence | Interpretation |
|---|---|---|
| ≥ 0.8 | High | Well-anchored, reliable interpolation |
| 0.5–0.8 | Moderate | Reduced gene recovery — introgression, assembly gap, or diverged region |
| < 0.5 | Low | Poor recovery — coordinates unreliable |

## Python

```python
from cs_coordinate_converter import CSCoordinateConverter

conv = CSCoordinateConverter("{args.conversion_dir}")

# Single position
tgt_chr, tgt_pos, conf = conv.convert("Chr1A", 500_000_000, "Mace")
print(f"Chr1A:500Mb -> {{tgt_chr}}:{{tgt_pos}} ({{conf:.0%}} gene recovery)")

# Region
tgt_chr, start, end, conf = conv.convert_region("Chr1A", 490e6, 510e6, "Mace")

# BED file
df = conv.convert_bed("my_regions.bed", "SY_Mattis", output_file="converted.tsv")

# List targets
print(conv.available_targets())
```

## CLI
```bash
# Single position
python cs_coordinate_converter.py --tables-dir {args.conversion_dir} \\
    --target Mace --chr Chr1A --pos 500000000

# Region
python cs_coordinate_converter.py --tables-dir {args.conversion_dir} \\
    --target Mace --chr Chr1A --start 490000000 --end 510000000

# BED file
python cs_coordinate_converter.py --tables-dir {args.conversion_dir} \\
    --target SY_Mattis --bed regions.bed --output converted.tsv
```

## R
```r
source("cs_coordinate_converter.R")
conv <- load_cs_converter("{args.conversion_dir}")

# Single position
res <- cs_convert(conv, "Chr1A", 500e6, "Mace")
cat(res$tgt_chr, res$tgt_pos, res$anchor_fraction, "\\n")

# Region
res <- cs_convert_region(conv, "Chr1A", 490e6, 510e6, "Mace")

# BED data frame
result_df <- cs_convert_bed(conv, my_bed_df, "SY_Mattis")
```
""")
    print(f"Written: {readme_out}", file=sys.stderr)


if __name__ == "__main__":
    main()
