#!/usr/bin/env python3
"""
03_generate_converter.py
========================
Generates ready-to-use coordinate conversion utilities:
  - cs_coordinate_converter.py  (Python class, importable)
  - cs_coordinate_converter.R   (R functions)

Both load the conversion tables on demand and provide:
  convert(cs_chr, cs_position, target_name) -> (tgt_chr, tgt_position, confidence)
  convert_region(cs_chr, cs_start, cs_end, target_name) -> (tgt_chr, tgt_start, tgt_end)
  convert_bed(input_bed, target_name) -> DataFrame
"""

import argparse
import sys
from pathlib import Path


PYTHON_CONVERTER = '''#!/usr/bin/env python3
"""
cs_coordinate_converter.py
==========================
Auto-generated by 03_generate_converter.py

Converts coordinates from IWGSC CS RefSeq v2.1 to target wheat assemblies.

Usage
-----
from cs_coordinate_converter import CSCoordinateConverter

conv = CSCoordinateConverter("/path/to/conversion_tables")

# Single position
tgt_chr, tgt_pos, confidence = conv.convert("chr1A", 500_000_000, "Mace")

# Region
tgt_chr, tgt_start, tgt_end = conv.convert_region("chr1A", 490e6, 510e6, "Mace")

# BED file
result_df = conv.convert_bed("my_regions.bed", "SY_Mattis")

# List available targets
print(conv.available_targets())

# List chromosomes for a target
print(conv.available_chromosomes("Mace"))
"""

import gzip
import sys
from functools import lru_cache
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.interpolate import interp1d


class CSCoordinateConverter:
    """
    Converts CS v2.1 coordinates to target assembly coordinates using
    precomputed spline conversion tables.
    """
    
    def __init__(self, conversion_tables_dir):
        """
        Parameters
        ----------
        conversion_tables_dir : str | Path
            Directory containing subdirectories for each target assembly,
            each containing <chr>_conversion.tsv.gz files.
        """
        self.conv_dir = Path(conversion_tables_dir)
        if not self.conv_dir.exists():
            raise FileNotFoundError(f"Conversion tables directory not found: {self.conv_dir}")
        
        self._tables = {}  # Cache: (target, chr) -> DataFrame
    
    def available_targets(self):
        """Return list of available target assembly names."""
        return sorted([d.name for d in self.conv_dir.iterdir() if d.is_dir()])
    
    def available_chromosomes(self, target_name):
        """Return list of chromosomes with conversion tables for a target."""
        tgt_dir = self.conv_dir / target_name
        if not tgt_dir.exists():
            raise ValueError(f"Target not found: {target_name}")
        return sorted([
            f.name.replace("_conversion.tsv.gz", "")
            for f in tgt_dir.glob("*_conversion.tsv.gz")
        ])
    
    def _load_table(self, target_name, cs_chr):
        """Load (and cache) conversion table for a target/chromosome pair."""
        key = (target_name, cs_chr)
        if key in self._tables:
            return self._tables[key]
        
        table_file = self.conv_dir / target_name / f"{cs_chr}_conversion.tsv.gz"
        if not table_file.exists():
            # Try without chr prefix
            alt_chr = cs_chr.replace("chr", "").replace("Chr", "")
            table_file = self.conv_dir / target_name / f"{alt_chr}_conversion.tsv.gz"
            if not table_file.exists():
                raise FileNotFoundError(
                    f"No conversion table for {target_name}/{cs_chr}. "
                    f"Available: {self.available_chromosomes(target_name)}"
                )
        
        df = pd.read_csv(table_file, sep="\\t", compression="gzip")
        self._tables[key] = df
        return df
    
    def _get_interpolator(self, target_name, cs_chr):
        """Build fast linear interpolator from table (cached)."""
        cache_key = f"interp_{target_name}_{cs_chr}"
        if hasattr(self, cache_key):
            return getattr(self, cache_key)
        
        df = self._load_table(target_name, cs_chr)
        tgt_chr = df["tgt_chr"].iloc[0]
        
        interp_cs = interp1d(
            df["cs_pos"].values,
            df["tgt_pos"].values,
            kind="linear",
            bounds_error=False,
            fill_value=(df["tgt_pos"].iloc[0], df["tgt_pos"].iloc[-1])
        )
        interp_density = interp1d(
            df["cs_pos"].values,
            df["anchor_density_5Mb"].values,
            kind="linear",
            bounds_error=False,
            fill_value=0
        )
        
        result = (tgt_chr, interp_cs, interp_density)
        setattr(self, cache_key, result)
        return result
    
    def convert(self, cs_chr, cs_position, target_name):
        """
        Convert a single CS position to target coordinates.
        
        Parameters
        ----------
        cs_chr : str
            CS chromosome (e.g. 'chr1A', '1A')
        cs_position : int
            Position in CS assembly (1-based or 0-based, consistent with your GFF)
        target_name : str
            Name of target assembly (must match directory name)
        
        Returns
        -------
        tgt_chr : str
        tgt_position : int
        anchor_density : int
            Number of gene anchors within 5 Mb (higher = more reliable)
        """
        tgt_chr, interp_pos, interp_density = self._get_interpolator(target_name, cs_chr)
        tgt_pos = int(np.round(interp_pos(cs_position)))
        density = int(np.round(interp_density(cs_position)))
        return tgt_chr, tgt_pos, density
    
    def convert_region(self, cs_chr, cs_start, cs_end, target_name):
        """
        Convert a CS region to target coordinates.
        
        Note: For inversions, tgt_start may be > tgt_end.
        The returned region is always in (min, max) order.
        
        Returns
        -------
        tgt_chr : str
        tgt_start : int
        tgt_end : int
        mean_density : float
        """
        tgt_chr, interp_pos, interp_density = self._get_interpolator(target_name, cs_chr)
        tgt_start = int(np.round(interp_pos(cs_start)))
        tgt_end = int(np.round(interp_pos(cs_end)))
        
        # Sample density across region
        sample_points = np.linspace(cs_start, cs_end, min(20, int((cs_end - cs_start) / 100000) + 2))
        mean_density = float(np.mean(interp_density(sample_points)))
        
        return tgt_chr, min(tgt_start, tgt_end), max(tgt_start, tgt_end), mean_density
    
    def convert_bed(self, bed_file, target_name, output_file=None):
        """
        Convert all regions in a BED file to target coordinates.
        
        Parameters
        ----------
        bed_file : str | Path
        target_name : str
        output_file : str | Path | None
            If provided, save result as TSV
        
        Returns
        -------
        DataFrame with converted coordinates
        """
        df = pd.read_csv(bed_file, sep="\\t", header=None, comment="#")
        n_cols = len(df.columns)
        col_names = ["cs_chr", "cs_start", "cs_end"] + [f"col{i}" for i in range(3, n_cols)]
        df.columns = col_names
        
        results = []
        failed = 0
        
        for _, row in df.iterrows():
            try:
                tgt_chr, tgt_start, tgt_end, density = self.convert_region(
                    row["cs_chr"], row["cs_start"], row["cs_end"], target_name
                )
                result_row = {
                    "cs_chr": row["cs_chr"],
                    "cs_start": row["cs_start"],
                    "cs_end": row["cs_end"],
                    "tgt_chr": tgt_chr,
                    "tgt_start": tgt_start,
                    "tgt_end": tgt_end,
                    "anchor_density": density,
                }
                # Preserve additional BED columns
                for i in range(3, n_cols):
                    result_row[f"col{i}"] = row[f"col{i}"]
                results.append(result_row)
            except (FileNotFoundError, KeyError) as e:
                failed += 1
                if failed <= 5:
                    print(f"WARN: Could not convert {row[\'cs_chr\']}:{row[\'cs_start\']}-{row[\'cs_end\']}: {e}",
                          file=sys.stderr)
        
        result_df = pd.DataFrame(results)
        
        if output_file:
            result_df.to_csv(output_file, sep="\\t", index=False)
        
        if failed > 0:
            print(f"Total failed conversions: {failed}/{len(df)}", file=sys.stderr)
        
        return result_df
    
    def batch_convert(self, positions_dict, target_name):
        """
        Convert multiple positions efficiently.
        
        Parameters
        ----------
        positions_dict : dict
            {\'query_id\': (cs_chr, cs_pos), ...}
        target_name : str
        
        Returns
        -------
        dict : {\'query_id\': (tgt_chr, tgt_pos, density), ...}
        """
        results = {}
        for qid, (cs_chr, cs_pos) in positions_dict.items():
            try:
                results[qid] = self.convert(cs_chr, cs_pos, target_name)
            except Exception as e:
                results[qid] = (None, None, 0)
        return results


# ============================================================
# CLI interface
# ============================================================
if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Convert CS v2.1 coordinates")
    parser.add_argument("--tables-dir", required=True)
    parser.add_argument("--target", required=True)
    parser.add_argument("--chr", dest="cs_chr")
    parser.add_argument("--pos", type=int)
    parser.add_argument("--start", type=int)
    parser.add_argument("--end", type=int)
    parser.add_argument("--bed", help="BED file to convert")
    parser.add_argument("--output", help="Output file for BED conversion")
    parser.add_argument("--list-targets", action="store_true")
    args = parser.parse_args()
    
    conv = CSCoordinateConverter(args.tables_dir)
    
    if args.list_targets:
        print("Available targets:", ", ".join(conv.available_targets()))
    elif args.bed:
        result = conv.convert_bed(args.bed, args.target, args.output)
        if not args.output:
            print(result.to_csv(sep="\\t", index=False), end="")
    elif args.cs_chr and args.pos:
        tgt_chr, tgt_pos, density = conv.convert(args.cs_chr, args.pos, args.target)
        print(f"{args.cs_chr}:{args.pos} -> {tgt_chr}:{tgt_pos} (anchor_density={density})")
    elif args.cs_chr and args.start and args.end:
        tgt_chr, tgt_start, tgt_end, density = conv.convert_region(
            args.cs_chr, args.start, args.end, args.target
        )
        print(f"{args.cs_chr}:{args.start}-{args.end} -> {tgt_chr}:{tgt_start}-{tgt_end} "
              f"(mean_density={density:.1f})")
    else:
        parser.print_help()
'''


R_CONVERTER = '''# =============================================================
# cs_coordinate_converter.R
# =============================================================
# Auto-generated coordinate converter for CS v2.1 -> target assemblies
#
# Usage:
#   source("cs_coordinate_converter.R")
#   conv <- load_cs_converter("/path/to/conversion_tables")
#
#   # Single position
#   result <- cs_convert(conv, "chr1A", 500e6, "Mace")
#
#   # Region
#   result <- cs_convert_region(conv, "chr1A", 490e6, 510e6, "Mace")
#
#   # BED data frame
#   result_df <- cs_convert_bed(conv, my_bed_df, "SY_Mattis")
#   
#   # List targets
#   cs_list_targets(conv)
# =============================================================

library(data.table)

#\' Load coordinate converter from tables directory
#\' @param tables_dir Path to conversion_tables/ directory
#\' @return Converter object (list with tables and functions)
load_cs_converter <- function(tables_dir) {
  if (!dir.exists(tables_dir)) {
    stop(paste("Conversion tables directory not found:", tables_dir))
  }
  
  conv <- list(
    tables_dir = tables_dir,
    cache = list()
  )
  class(conv) <- "CSConverter"
  return(conv)
}

#\' List available target assemblies
cs_list_targets <- function(conv) {
  dirs <- list.dirs(conv$tables_dir, full.names = FALSE, recursive = FALSE)
  return(sort(dirs))
}

#\' List available chromosomes for a target
cs_list_chromosomes <- function(conv, target_name) {
  tgt_dir <- file.path(conv$tables_dir, target_name)
  files <- list.files(tgt_dir, pattern = "_conversion\\\\.tsv\\\\.gz$")
  gsub("_conversion\\\\.tsv\\\\.gz", "", files)
}

# Internal: load and cache a conversion table
.load_table <- function(conv, target_name, cs_chr) {
  key <- paste(target_name, cs_chr, sep = "_")
  
  if (!is.null(conv$cache[[key]])) {
    return(conv$cache[[key]])
  }
  
  table_file <- file.path(conv$tables_dir, target_name,
                          paste0(cs_chr, "_conversion.tsv.gz"))
  
  if (!file.exists(table_file)) {
    # Try without chr prefix
    alt_chr <- gsub("^chr", "", cs_chr)
    table_file <- file.path(conv$tables_dir, target_name,
                            paste0(alt_chr, "_conversion.tsv.gz"))
    if (!file.exists(table_file)) {
      stop(paste("No conversion table for", target_name, cs_chr))
    }
  }
  
  dt <- fread(table_file)
  conv$cache[[key]] <<- dt
  return(dt)
}

#\' Convert a single CS position to target coordinates
#\' @param conv Converter object from load_cs_converter()
#\' @param cs_chr CS chromosome name (e.g. "chr1A")  
#\' @param cs_pos CS position (integer)
#\' @param target_name Target assembly name
#\' @return Named list: tgt_chr, tgt_pos, anchor_density
cs_convert <- function(conv, cs_chr, cs_pos, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  
  tgt_chr <- dt$tgt_chr[1]
  tgt_pos <- as.integer(approx(dt$cs_pos, dt$tgt_pos, xout = cs_pos, 
                                rule = 2)$y)
  density <- as.integer(approx(dt$cs_pos, dt$anchor_density_5Mb, xout = cs_pos,
                                rule = 2)$y)
  
  return(list(tgt_chr = tgt_chr, tgt_pos = tgt_pos, anchor_density = density))
}

#\' Convert a CS region to target coordinates
#\' @return Named list: tgt_chr, tgt_start, tgt_end, mean_anchor_density
cs_convert_region <- function(conv, cs_chr, cs_start, cs_end, target_name) {
  dt <- .load_table(conv, target_name, cs_chr)
  
  tgt_chr <- dt$tgt_chr[1]
  tgt_start <- as.integer(approx(dt$cs_pos, dt$tgt_pos, xout = cs_start, rule = 2)$y)
  tgt_end   <- as.integer(approx(dt$cs_pos, dt$tgt_pos, xout = cs_end,   rule = 2)$y)
  
  sample_pts <- seq(cs_start, cs_end, length.out = 20)
  mean_density <- mean(approx(dt$cs_pos, dt$anchor_density_5Mb, xout = sample_pts, rule = 2)$y)
  
  return(list(
    tgt_chr = tgt_chr,
    tgt_start = min(tgt_start, tgt_end),
    tgt_end   = max(tgt_start, tgt_end),
    mean_anchor_density = round(mean_density, 1)
  ))
}

#\' Convert a data frame of BED regions
#\' @param conv Converter
#\' @param bed_df Data frame with columns: chr, start, end (and optional extras)
#\' @param target_name Target assembly name
#\' @return Data frame with added tgt_chr, tgt_start, tgt_end columns
cs_convert_bed <- function(conv, bed_df, target_name) {
  colnames(bed_df)[1:3] <- c("cs_chr", "cs_start", "cs_end")
  
  results <- lapply(seq_len(nrow(bed_df)), function(i) {
    tryCatch({
      r <- cs_convert_region(conv,
                             bed_df$cs_chr[i],
                             bed_df$cs_start[i], 
                             bed_df$cs_end[i],
                             target_name)
      data.frame(
        cs_chr   = bed_df$cs_chr[i],
        cs_start = bed_df$cs_start[i],
        cs_end   = bed_df$cs_end[i],
        tgt_chr  = r$tgt_chr,
        tgt_start = r$tgt_start,
        tgt_end   = r$tgt_end,
        anchor_density = r$mean_anchor_density
      )
    }, error = function(e) {
      warning(paste("Failed to convert row", i, ":", conditionMessage(e)))
      NULL
    })
  })
  
  result_df <- do.call(rbind, Filter(Negate(is.null), results))
  
  # Append extra BED columns if present
  if (ncol(bed_df) > 3) {
    extra <- bed_df[, 4:ncol(bed_df), drop = FALSE]
    result_df <- cbind(result_df, extra[!sapply(results, is.null), , drop = FALSE])
  }
  
  return(result_df)
}

#\' Print summary of available targets and chromosomes
print.CSConverter <- function(conv, ...) {
  targets <- cs_list_targets(conv)
  cat("CS Coordinate Converter\\n")
  cat("Tables dir:", conv$tables_dir, "\\n")
  cat("Available targets:", paste(targets, collapse = ", "), "\\n")
}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--conversion-dir", required=True)
    parser.add_argument("--target-names", nargs="+", required=True)
    parser.add_argument("--output-dir", required=True)
    args = parser.parse_args()
    
    outdir = Path(args.output_dir)
    outdir.mkdir(parents=True, exist_ok=True)
    
    # Write Python converter
    py_out = outdir / "cs_coordinate_converter.py"
    with open(py_out, "w") as fh:
        fh.write(PYTHON_CONVERTER)
    print(f"Written: {py_out}", file=sys.stderr)
    
    # Write R converter
    r_out = outdir / "cs_coordinate_converter.R"
    with open(r_out, "w") as fh:
        fh.write(R_CONVERTER)
    print(f"Written: {r_out}", file=sys.stderr)
    
    # Write a quick usage README
    readme_out = outdir / "CONVERTER_USAGE.md"
    with open(readme_out, "w") as fh:
        fh.write(f"""# CS Coordinate Converter — Usage Guide

## Available targets
{chr(10).join(f'- {t}' for t in args.target_names)}

## Python

```python
from cs_coordinate_converter import CSCoordinateConverter

conv = CSCoordinateConverter("{args.conversion_dir}")

# Single position
tgt_chr, tgt_pos, density = conv.convert("chr1A", 500_000_000, "Mace")
print(f"chr1A:500Mb -> {{tgt_chr}}:{{tgt_pos}} (density={{density}})")

# Region
tgt_chr, start, end, density = conv.convert_region("chr1A", 490e6, 510e6, "Mace")

# BED file
df = conv.convert_bed("my_regions.bed", "SY_Mattis", output_file="converted.tsv")

# List targets
print(conv.available_targets())
```

## CLI (Python)
```bash
python cs_coordinate_converter.py --tables-dir {args.conversion_dir} \\
    --target Mace --chr chr1A --pos 500000000

python cs_coordinate_converter.py --tables-dir {args.conversion_dir} \\
    --target SY_Mattis --bed regions.bed --output converted.tsv
```

## R
```r
source("cs_coordinate_converter.R")
conv <- load_cs_converter("{args.conversion_dir}")

# Single position
res <- cs_convert(conv, "chr1A", 500e6, "Mace")

# Region
res <- cs_convert_region(conv, "chr1A", 490e6, 510e6, "Mace")

# BED data frame
result_df <- cs_convert_bed(conv, my_bed_df, "SY_Mattis")
```

## Confidence/quality
Each conversion returns `anchor_density` = number of gene anchors within ±5 Mb.
- **≥10**: high confidence
- **5–10**: moderate confidence (sparse region, possibly pericentromeric)
- **<5**: low confidence (extrapolated or poorly mapped region)
""")
    
    print(f"Written: {readme_out}", file=sys.stderr)


if __name__ == "__main__":
    main()
